name: Build/Test
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: trigger-jenkins
        uses: iadonkey/build-jenkins-job@1.1.0
        with:
          jenkins-url: http://www.infiniteautomation.at:8888
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-job: Iaf/build_library/main
          jenkins-job-params: '{"SCM":"${{ github.server_url }}/${{ github.repository }}.git","TC_VERSION":"TC3.1.4024.17","VERSION":"","REVISION":"${{ github.sha }}"}'
          jenkins-wait-job: wait
          jenkins-ssl-verify: false
      - name: Copy Artifact
        run: |
          curl --insecure -u '${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}' https://www.infiniteautomation.at:8883/job/Iaf/job/build_library/job/main/${{ steps.trigger-jenkins.outputs.job_build_number }}/artifact/\*zip\*/archive.zip -o archive.zip
          unzip archive.zip
      - name: Publish Unittest
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: archive/test/TcUnit_xUnit_results.xml
