name: Build/Test
on:
  push:
    branches:
      - main
    paths:
      - 'Struckig/**'
      - 'test/**'
      - 'example/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ZEUGWERK_API_USERNAME }}
          password: ${{ secrets.ZEUGWERK_API_PASSWORD }}
      - name: Publish Unittest
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: archive/test/TcUnit_xUnit_results.xml
