name: Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Documentation:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Generate
        id: trigger-jenkins
        uses: iadonkey/build-jenkins-job@1.1.0
        with:
          jenkins-url: http://www.zeugwerk.at:8888
          jenkins-token: ${{ secrets.JENKINS_TOKEN }}
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-job: jobs/doc
          jenkins-job-params: '{"SCM":"${{ github.server_url }}/${{ github.repository }}.git", "REVISION":"${{ github.sha }}"}'
          jenkins-wait-job: wait
          jenkins-ssl-verify: false
      - name: Copy Artifact
        run: |
          curl --insecure -u '${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}' https://www.zeugwerk.at:8883/job/jobs/job/doc/${{ steps.trigger-jenkins.outputs.job_build_number }}/artifact/\*zip\*/archive.zip -o archive.zip
          unzip archive.zip
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: archive/documentation/html
