name: Generate Unittest
on:
  workflow_dispatch:
jobs:
  Build:
    name: Generate Unittest
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install pybind11
      run: |
        cd ruckig
        git clone https://github.com/pybind/pybind11.git
        cd pybind11
        git checkout v2.6.0
    - name: Set compiler version and patch C++11
      if: runner.os == 'Linux' && matrix.compiler == 'gcc' && matrix.version == '5'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
        echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        sh patch-c++11.sh inplace
    - name: Configure and make
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildDirectory: "${{ github.workspace }}/ruckig/build"
        cmakeBuildType: 'Release'
        cmakeAppendedArgs: '-DBUILD_PYTHON_MODULE=ON -DBUILD_EXAMPLES=ON -DBUILD_BENCHMARK=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=. -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG=.'
    - name: Install python module
      run: |
        cd ruckig
        python setup.py install
    - name: Create Unittest
      run: |
        python test/generate_testsuite.py
        cp test/GeneratedTest.TcPOU test/Struckig_unittest/struckig_unittest/POUs/GeneratedTest.TcPOU
        
        
